# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-25 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generate_datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Report_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, unique=True)),
                ('description', models.TextField(default='')),
                ('layout_json', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='report.Report_type'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
