# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-25 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('start_time', models.TimeField(default='')),
                ('end_time', models.TimeField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='end_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_lesson_profile', to='booking.Lesson'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.Room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_lesson_profile', to='booking.Lesson'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
