# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-25 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('content', models.TextField(default='')),
                ('announce_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('instruction', models.TextField(default='')),
                ('handin_method', models.CharField(choices=[('U', 'Upload'), ('T', 'Text')], default='D', max_length=1)),
                ('deadline_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('fullmark', models.PositiveSmallIntegerField(default=100)),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment_pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_json', models.TextField(default='')),
                ('mark', models.PositiveSmallIntegerField(default=100)),
                ('assignment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='classroom.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('shortcode', models.CharField(default='', max_length=255, unique=True)),
                ('description', models.TextField(default='')),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Close')], default='O', max_length=1)),
                ('creator', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom_note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='classroom.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('path', models.FileField(default='', upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Material_ext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_name', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='', max_length=255)),
                ('type_description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('content', models.TextField(default='')),
                ('publish_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('P', 'Published'), ('D', 'Drafted'), ('T', 'Trashed')], default='D', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User_assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('role', models.CharField(choices=[('STU', 'Student'), ('TEA', 'Teacher'), ('ADM', 'Admin'), ('VIS', 'Visitor')], default='STU', max_length=3)),
                ('classroom', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='classroom.Classroom')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.AddField(
            model_name='material_ext',
            name='material_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='classroom.Material_type'),
        ),
        migrations.AddField(
            model_name='material',
            name='material_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='classroom.Material_type'),
        ),
        migrations.AddField(
            model_name='material',
            name='uploader',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='classroom.User_assignment'),
        ),
        migrations.AddField(
            model_name='classroom_note',
            name='note',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='classroom.Note'),
        ),
        migrations.AddField(
            model_name='assignment_pool',
            name='user_assign',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='classroom.User_assignment'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='classroom',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='classroom.Classroom'),
        ),
        migrations.AddField(
            model_name='announce',
            name='classroom',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='classroom.Classroom'),
        ),
    ]
