# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-15 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20160315_1043'),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_json', models.TextField(default='')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom_note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='announce',
            name='announce_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='announce',
            name='classroom',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='classroom.Classroom'),
        ),
        migrations.AddField(
            model_name='announce',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='announce',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='assignment',
            name='deadline_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='assignment',
            name='fullmark',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='assignment',
            name='handin_method',
            field=models.CharField(choices=[('U', 'Upload'), ('T', 'Text')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='assignment',
            name='instruction',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='assignment',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='classroom',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='classroom',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='classroom',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Close')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='exercise',
            name='instruction',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='exercise',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='material',
            name='classroom',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='classroom.Classroom'),
        ),
        migrations.AddField(
            model_name='material',
            name='create_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='material',
            name='path',
            field=models.FileField(default='', upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='material',
            name='uploader',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='material_ext',
            name='ext_name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='material_ext',
            name='material_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='classroom.Material_type'),
        ),
        migrations.AddField(
            model_name='material_type',
            name='type_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='material_type',
            name='type_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='note',
            name='publish_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('P', 'Published'), ('D', 'Drafted'), ('T', 'Trashed')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_assignment',
            name='assigment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='classroom.Assignment'),
        ),
        migrations.AddField(
            model_name='user_assignment',
            name='assign_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user_assignment',
            name='role',
            field=models.CharField(choices=[('STU', 'Student'), ('TEA', 'Teacher'), ('ADM', 'Admin'), ('VIS', 'Visitor')], default='STU', max_length=3),
        ),
        migrations.AddField(
            model_name='user_assignment',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='classroom_note',
            name='classroom',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='classroom.Classroom'),
        ),
        migrations.AddField(
            model_name='classroom_note',
            name='note',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='classroom.Note'),
        ),
    ]
