# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-25 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Event_terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_term', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Time_meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_obj', models.DateTimeField(auto_now_add=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_generated', models.BooleanField(default=False)),
                ('calender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Calendar')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Activity_event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.AddField(
            model_name='activity_event',
            name='activity_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Event_terms'),
        ),
        migrations.AddField(
            model_name='activity_event',
            name='end_date',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='end_time_profile', to='timetable.Time_meta'),
        ),
        migrations.AddField(
            model_name='activity_event',
            name='start_date',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='start_time_profile', to='timetable.Time_meta'),
        ),
    ]
