# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-14 04:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20160314_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='system_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='time_meta',
            name='time_obj',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 14, 12, 21, 54, 839130), unique=True),
        ),
    ]
