# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-14 04:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20160314_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_meta',
            name='time_obj',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 14, 12, 22, 52, 990939), unique=True),
        ),
    ]
