# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-14 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20160314_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_meta',
            name='time_obj',
            field=models.DateTimeField(auto_now_add=True, unique=True),
        ),
    ]
