# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(default='', max_length=255)),
                ('parent_type', models.CharField(choices=[('F', 'Father'), ('M', 'Mother'), ('G', 'Guardian'), ('O', 'Other')], default='', max_length=1)),
                ('parent_phone', models.CharField(default='', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_user', models.CharField(choices=[('STU', 'Student'), ('TEA', 'Teacher'), ('STA', 'Staff'), ('ALU', 'Alumni'), ('ADM', 'Admin')], default='STU', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=255)),
                ('firstname', models.CharField(default='', max_length=255)),
                ('lastname', models.CharField(default='', max_length=255)),
                ('password_hash', models.CharField(default='', max_length=64)),
                ('card_id', models.CharField(default='', max_length=20)),
                ('strn_code', models.CharField(default='', max_length=12)),
                ('sams_code', models.CharField(default='', max_length=12)),
                ('jupas_app_code', models.CharField(default='', max_length=32)),
                ('barcode', models.CharField(default='', max_length=32)),
                ('birth_date', models.DateField(null=True)),
                ('hkid_card', models.CharField(default='', max_length=12)),
                ('address', models.TextField(default='')),
                ('phone', models.CharField(default='', max_length=24)),
                ('mobile', models.CharField(default='', max_length=24)),
                ('email', models.EmailField(default='', max_length=254)),
                ('national', models.CharField(default='', max_length=24)),
                ('location_of_birth', models.CharField(default='', max_length=24)),
                ('intake_date', models.CharField(default='', max_length=24)),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='parent_contact',
            name='user',
            field=models.ManyToManyField(to='user.User'),
        ),
    ]
