# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-25 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission_meta',
            old_name='permission_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='permission_meta',
            old_name='permission_key',
            new_name='key',
        ),
        migrations.AddField(
            model_name='permission_meta',
            name='level',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
