# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20160308_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_token',
            field=models.CharField(default='', max_length=32),
        ),
    ]
