# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20160308_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Class_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='', max_length=2)),
                ('class_description', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='class_assignment',
            name='class_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Class_code'),
        ),
        migrations.AddField(
            model_name='class_assignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
