# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-10 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20160309_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Permission_key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_key', models.CharField(default='', max_length=255)),
                ('permission_description', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='permission',
            name='permission_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Permission_key'),
        ),
        migrations.AddField(
            model_name='permission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
