# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-10 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20160310_0529'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission_key',
            new_name='Permission_meta',
        ),
    ]
