# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-14 06:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20160310_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_assignment',
            name='class_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='timeout',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 14, 11, 5, 43, 852815, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='user',
            name='sex_code',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='', max_length=96),
        ),
    ]
