# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 04:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20160310_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='timeout',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 11, 9, 51, 1, 896721)),
        ),
    ]
