# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-12 08:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_session_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='timeout',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 12, 21, 43, 47, 863808)),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='', max_length=96),
        ),
    ]
