# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-15 01:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20160314_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='timeout',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 15, 6, 32, 50, 112645, tzinfo=utc)),
        ),
    ]
