# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-15 02:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20160315_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='timeout',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 15, 7, 38, 40, 1893, tzinfo=utc)),
        ),
    ]
